### ISSUE TITLE
p2p.Server connections not being tracked properly

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1172]
`p2p.Server` uses [meteredConnection](https://github.com/celo-org/celo-blockchain/blob/master/p2p/metrics.go#L114) to monitor connections (ingress/egress connections; bandwidth usage)

Nodes on mainnet currently see a `"Metered peer count reached the limit"` warning that indicates the nodes has more the 1024 active connections, still when checking active connections, there's no more than 100 (as indicated by the max peers flag) 

This log message, seems to imply one of two things:
   1. We are not tracking close connection events properly
   2. We don't close the connections but we do loose track of them internally

Both scenarios don't look well, so we need to investigate and solve this issue

**Comment by oneeman** [comment]
These messages are based on a metric called `meteredPeerCount` (https://github.com/celo-org/celo-blockchain/blob/master/p2p/metrics.go#L55/).  This metric in incremented in `handshakeDone()` and decremented in `Close()`.  There is another metric in the same file, `activePeerGauge`, which is similarly incremented and decremented, and while `meteredPeerCount` gets as high as 1024, `activePeerGauge` remains below the node's max peers limit, as it should.

From the code it can be seen that there is only one way for those two to get out of step with each other, which is if (for a particular connection), `Close()` is called either before or concurrently with `handshakeDone()`, such that line 201 (https://github.com/celo-org/celo-blockchain/blob/master/p2p/metrics.go#L201) gets executed before line 183 (https://github.com/celo-org/celo-blockchain/blob/master/p2p/metrics.go#L201).  This could happen if a connection is closed immediately after it's established, which has in fact been happening due to a separate upstream bug: the dialer does not take into account static dial connections when calculating whether it should start new dynamic dial connections, leading to the node attempting to form new dyndial connections even though it is already at its max peers limit, and so those new connections get disconnected right afterwards when the max peers check is done.  This bug has been fixed upstream in newer versions by this PR: https://github.com/ethereum/go-ethereum/pull/20592 .

However, it also bears noting that much of this metrics code, and the `meteredPeerCount` metric itself have been removed in newer versions of geth, so that once we merge those changes in, this warning would no longer exist, and so there is not much value in addressing it directly prior to that.
