### ISSUE TITLE
Merge Upstream to 1.9.22

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1179]
Bring upstream changes up to 1.9.22

**Comment by oneeman** [comment]
A few things to check off when doing this (this list is not exhaustive):
1. When https://github.com/ethereum/go-ethereum/pull/20592 is merged, it should fix https://github.com/celo-org/celo-blockchain/issues/1180, so that issue can be closed then.
2. When https://github.com/ethereum/go-ethereum/pull/20679 is merged, then https://github.com/celo-org/celo-blockchain/issues/1172 will no longer be a thing since the PR removes that metric and the associated code, so that issue can be closed then.
3. The new dialer (https://github.com/ethereum/go-ethereum/pull/20592) includes a breaking change in what `addStatic()` does.  Prior to this, if you call `addStatic` for a node that's already in static, but with a different address, it gets updated: https://github.com/ethereum/go-ethereum/blob/4ea9b62b5ce396c5609c100b8b2c05f11d1d7fac/p2p/dial.go#L111 .  After this, it does not get updated: https://github.com/ethereum/go-ethereum/blob/90caa2cabbd46c3e712eb7216bd668dd02bb15a8/p2p/dial.go#L276-L282 .  I'm not sure whether we are relying on the current behavior anywhere, so it's something to check and remedy if necessary.

**Comment by mcortesi** [comment]
Closing this now. We'll use individual issues for now on
