### ISSUE TITLE
Check if pending txs get retried or flushed and get the nonce gets reset when there is a stale nonce issue

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1189]
LightClient/FullNodes saves local transactions after it broadcast them. On the case of the network "forget" about this transactions, it seems transaction are not resent, and from the light client persepective the tx exists, and from the network one it doesn't. This creates a "nonce hole" which "brinks" the client.

We need to understand this issue better and see if it actually brick the client or if there's a way to avoid it. If sipmle, implement

**Comment by hbandura** [comment]
Updating here with the things I learned while investigating this issue:

Light and full nodes use different transaction pools. Light node implementation can be found in `light/txpool.go` while the full node implementation is available in `core/tx_pool.go`.  They don’t behave the same so this issue is not equal between the two. Since this issue was found by the load test, that uses the light client, and our focus on mobile, I’ll explain here what I saw in the light client.

1) Unlike the full node, the light client does not seem to store offline the tx pool contents. That is, if it gets rebooted, it starts from scratch. This is consistent with the issue we saw where restarting the light clients “fixed” the nonce hole issue.
2) Transactions are only sent to the network during the ‘Add’ and ‘AddBatch’ calls. They never get retried past that point. If the network discards them for some reason, the tx pool will keep them forever, since the light tx pool implementation does not have a limited size.
3) The nonce pre-add check compares the tx nonce with the highest available nonce between chain state nonce and pool nonce, with no overriding mechanism. Therefore, if tx with nonce X gets dropped from the network, but it’s still in the light pool, this situation is not recoverable (there’s an API for removing the tx but the implementation does not updates the nonce cache).
4) The `pool.relay.Send` function, used to send the tx to the network, has no error check. If it fails for some reason, the same situation arises (stale pool and nonce hole).

Non issue-related comments:

5) The AddBatch call does not updates the chainDb, while the Add call does
6) There’s a cache to ensure no tx is added twice, but it’s only working for valid transactions. If a tx can be crafted where the validation process is expensive while failing, it can be resent multiple times and could be a DDOS opportunity.
7) Unlimited pool size sounds fishy.
8) From a mobile perspective, even having a tx pool may not even make sense.
9) May not be relevant, but I found it confusing that the api allows to easily ask for the pool nonce but not the chain nonce for an address.

Overall, we could have different ways to change this:

A) Implement a new tx pool (or even no tx pool) for the mobile usage.
B) Add retries / eviction policy to transactions in the pool that the network doesn’t include in the chain.
C) Add a way to override a transaction nonce
