### ISSUE TITLE
Update command line description of light.serve flag default value

### ISSUE THREAD

**Issue by pranaymohan** [celo-org/celo-blockchain#1261]
**Describe the bug**
In the CLI flag description for `light.serve`, it says the default is set to 0, when in reality it's set to 50. Should be updated to reflect default.

**To Reproduce**
See current description: https://github.com/celo-org/celo-blockchain/blob/master/docs/docs/_interface/Command-Line-Options.md
```
  --light.serve value                 Maximum percentage of time allowed for serving LES requests (multi-threaded processing allows values over 100) (default: 0)
```

Default value is actually 50: 
https://github.com/celo-org/celo-blockchain/blob/v1.1.1/eth/config.go#L36

cc @oneeman @YazzyYaz

**Comment by oneeman** [comment]
Thanks @pranaymohan.  The mismatch is indeed a problem, but in this case zero is actually the value we want to change the default back to zero.  So I'm going to close this in favor of https://github.com/celo-org/celo-blockchain/issues/1262

**Comment by oneeman** [comment]
Looking at this again, that markdown file is out of date (whereas what you get using `--help` uses the actual default values specified in the code).  It looks like it was added in https://github.com/celo-org/celo-blockchain/pull/1075 and hasn't been updated since.  I don't know whether we should create a process to ensure it gets updated when needed, or whether we should get rid of it.  I will add this as an item in #1264.

cc: @mcortesi
