### ISSUE TITLE
Investigate Turbogeth and porting opportunities

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1321]
The objective of this task is to investigate turbogeth, and come up with potential opportunities to increase scalability.

The output for the task is to write a notion doc with the output of the research and a list of "worth looking into" directions. For most prominent directions, have an action plan, and how we can integrate those changes into celo-blockchain.

**Comment by hbandura** [comment]
On implementing turbogeth storage changes into celo blockchain

The celo / ethereum storage is conceptually a key value database, mapping accounts to state. In the case of contracts this state holds another key value inside storing the contract state/data. This is reflected in both EVM opcodes and also the EVM implementation. I confirmed this by looking at the code in `core/vm`, and its usage of the `StateDB` object.

However the database implementation does not just forward keys and values to an underlying key value database (e.g leveldb). Instead a new key value structure is built in the form of a trie, and uses leveldb to store the trie nodes (including leaf nodes, a.k.a state). Every node in this trie holds its childs' keys from the db. Therefore, to acquire the state of an account, one needs to make several sequential access to the underlying key value database, which may or may not result in disk accesses. The most likely reason for this design is that it simplifies the computation of the state root hash, at the expense of reading performance.

Turbogeth approach is to map account keys more directly to the underlying db, reducing the disk accesses needed to one. The state root hash computation can still be done with a data structure that holds the same intermediate tree hashes without the need of actually storing the leaf nodes.

This storage model change aligns with the current celo initiative to increase transaction throughput, more so than other (beneficial) changes the turbogeth project has made. This is why I recommend that we put some effort in scoping the task of implementing this change in celo-blockchain. We should find out not only the amount of work needed but also how parallelizable it is (is it a one-person job or can it be split somehow?), if both can implementations coexist in the same binary via some cmd line option or if it needs its own implementation branch. This will require a more hands-on approach which is why it should be a different issue.

It is important to note that the benefits from this change will be more evident as the database grows larger, since, the problem is present when many trie nodes are not cached in memory. Therefore it could be the case that in the near future it may not seem as a big leap forward, but it will definitely keep the performance at bay instead of degrading in time.
