### ISSUE TITLE
Rename our packages to not be called github.com/ethereum/go-ethereum/*

### ISSUE THREAD

**Issue by oneeman** [celo-org/celo-blockchain#1344]
## Description

In `go.mod`, rename our package to:

```
module github.com/celo-org/celo-blockchain
```

And update all the imports which say `github.com/ethereum/go-ethereum` to say `github.com/celo-org/celo-blockchain`.

Additionally, we should have some protection against accidentally importing anything from go-ethereum due to new imports added as part of a merge.  This could be part of CI, or maybe part of the build.  The key point is to ensure we are not pulling in go-ethereum packages.  Probably grepping `go.mod` would be sufficient, but this needs to be verified.

Or, as suggested by @trianglesphere, there may be a way to automate the renaming of imports using gofmt.  See https://spf13.com/post/go-fmt/

## Context

The current naming, besides being inaccurate, prevents third-party projects from adding both go-ethereum and celo-blockchain as dependencies if they need to.

**Comment by trianglesphere** [comment]
I'd also like to see if there is a git hook that we could use to do the renaming for us when pulling from upstream.

**Comment by mcortesi** [comment]
`go fmt` looks interesting. But if it takes too much, it should be easy to do a `sed` over all files and just search and replace.

**Comment by trianglesphere** [comment]
Go fmt looks like it's basically sed except a little specialized to go programs. It does come with a warning that it might be slow.

**Comment by asaj** [comment]
To elaborate on context I think the Keep folks working on tBTC are worried that this will block their progress in the near (1-2 weeks) term. They are not currently blocked.

**Comment by asaj** [comment]
The impact would be that they would need to produce an additional binary to support Celo rather than integrating it into the same binary that supports Ethereum

**Comment by pdyraga** [comment]
Thanks for bringing this issue @oneeman. To provide more color: as @asaj mentioned, our ECDSA client has `ethereum/go-ethereum` as a dependency. Now, given that we are adding Celo as the second host chain for tBTC, we need our ECDSA client to depend on `celo-blockchain` but we cannot do it given that `celo-blockchain` client module is named `ethereum/go-ethereum` and we are running into conflicts.

The business-level impact of not doing the rename is that we'll have to ship a separate ECDSA client binary for Celo and this will require staking providers [already working with Keep](https://blog.keep.network/how-to-stake-on-the-keep-network-20e6bc7db1e4) to configure separate Celo-specific deployments instead of just reusing what they already have.

Even if - for whatever reason - we decide to ship a separate binary for Celo, being able to import `github.com/celo-org/celo-blockchain` feels safer for us long-term. We have a set of [chain utils](https://github.com/keep-network/keep-common/tree/master/pkg/chain/ethereum) and [smart contract Go binding generators](https://github.com/keep-network/keep-common/tree/master/tools/generators/ethereum) and there might be a need to optimize some of them for Celo-specific features. Also, there is no guarantee Celo client Go API will always stay compatible with Ethereum Go API. Even if short-term we end up with some code duplication on our side, being able to implement chain code components addressing Celo specifically feels safer and may one day become a requirement.

We do understand that this change might be non-trivial on your side. Unfortunately, it will become a blocker even this week.  On our side, for this week and next week, it should be enough to know if you are for or against this change and if you decide to do the rename, we can work against the code pushed in https://github.com/celo-org/celo-blockchain/pull/1342 for now.

**Comment by trianglesphere** [comment]
Hi @pdyraga, we're going to be going ahead with this rename. For know go ahead and work off of #1342, and we'll get that incorporated into master in the next couple days to week.
