### ISSUE TITLE
Generate a rough estimate of impact and effort for integrating TurboGeth state DB and the Celo client

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1391]
In support of Milestone planning, which starts on March 3rd, we would like to have an estimate of impact and effort that can be used to assign priority and engineering time to the effort to integrate the TurboGeth state DB structure and the Celo client.

**Comment by hbandura** [comment]
After a timeboxed analysis of the turbogeth code and it's improvements over standard geth, I believe porting only the data model changes (which is the part we were mostly interestid in) would not be a simple task. While the code seems to be well structured, the difference with geth implies that too many things would have to be rewritten to maintain feature parity. Some rpc methods have been reimplemented and, without a detailed look of one by one of these changes, it is impossible to know if this was due to particular optimizations to that part of the code, or if this rewritings were forced due to the data model changes. A more detailed analysis could be done, but I don't think it's a good use of time to do so.

It is my impression that it would be much faster to port celo changes on top of turbogeth, than trying to dissect it and rewrite what's needed in order to merge the data changes to our codebase. While I feel the data model of turbogeth's makes sense, it is much more complex than the standard trie structure geth uses. Several buckets in the KV database are used (10+) holding different types of data (accounts, contract state, changesets, contractcode, intermediate trie hashes, and others). While most of the low level code can probably copied as-is, the interactions with the middle layers would need to be rewritten, and because of the reasons mentioned in the previous paragraph it is not trivial to know which ones can be left untouched with minor boiler plate code, and which ones need to be rethinked and/or also ported.

While probably time consuming, it's 100% possible to bring these changes if we want to. But just as right now we lack expertise on the specific technichal details of standard geth (which, admittedly, we are shortening that gap a bit every day), the 'making sure everything works' part by itself would also take some non trivial amount of time. 

If I were to eyeball an estimate on work needed (which I actually hate to do, because it feels to big to estimate without splitting it into smaller parts, which is also no easy feat) I would have to say that we probably need several months. I do believe that some parallelization can be achieved though: working at the low level and mid level (data model, vs evm interface/rpc/miner/txpool interface/boilerplate plugging) could probably be done at the same time. To note: turbogeth claims in its webpage (haven't checked in the code) that it does not possess fast syncing ability. I'm not sure how that could impact our implementation of fast/lightest sync modes. In summary, I would go with 4 months of 2 engineers full time (better safe than sorry when writing estimates like this). Again, I believe the variance of this estimate is huge and it could take anywhere from half to double the time.

Regarding the potential impact of the changes: turbogeth claims a large reduction in space used (roughly 20%-25% of what a standard geth node uses). On speed, historical storage queries in any point in time can be some orders of magnitude faster (I'm not sure how useful this is though, but it's impressive). I have not found precise comparisons of full syncing time of geth vs turbogeth, but looking at older posts from 2018/2019 it would seem that we are talking about a few weeks vs few days difference, again, impressive. I was not able to find information evm transaction execution performance, which is what I was most interested in, I have to assume it's faster due to faster data access and proved by the faster syncing time, but still no numbers to show.

I believe that the idea of turbogeth's datamodel is great, and my recommendation would be to find out a way to probably move forward in that direction. But I'm not 100% sure if porting their code as-is is our best way to go. Given the fact that we are a proof of stake with minimal (or none?) need for reorgs, there may be some substantial differences to the data model that we could make on turbogeth's which may be more suitable for our use cases.

As a next step, I think that first trying to accurately find out our bottle necks during block execution (the point we are currently trying to optimize) and brainstorm possibilities of improving that specific part without making huge changes first, and only start with plans to a data model migration as a future step. E.g I believe that either some caching or de-normalization of the canonical chain's head state will probably result in similar performance improvements, albeit with an increase in disk size.
