### ISSUE TITLE
Write up notes on TurboGeth as it related to the Celo client

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1392]
To facilitate knowledge sharing, and a better collective understanding or the work required, we should have written up notes that describe the primary differences between the Geth / Celo client and TurboGeth. The goal is to allow any engineer on the Blockchain team to have a high-level understanding of the work that will be required and contribute to discussion around any design decisions involved.

**Comment by hbandura** [comment]
Turgobeth engineering differences in data model

In standard geth, from the EVM perspective, the state accessor is the object called StateDB. In TurboGETH, it's IntraBlockState (IBS), but it's interface for this purpose is the same. The main difference is that IBS purpose is to buffer changes to the state, and does not have any direct references or dependencies to lower layers like StateDB has (e.g trie). Instead, its Commit method has to be called with a StateWriter. The IBS is created with a StateReader, and it seems that it's always the PlainStateReader type (unhashed keys).

From blockchain.writeBlockWithState we can see that IBS.Commit is called twice with two different writers. One is the plain state writer, and the other one a TrieDbStateWriter. Both end up writing to a bucket in the key value database, but the latter hashes its keys according to what the ethereum trie keys should be. From the EVM the Plain Reader is used (reading from the bucket with plain keys).

Since state and storage are not stored as a trie structure like in geth, the root hash has to be calculated in a slightly different way. It's done from state_processor in the following way: first a trie structure is created in memory that replicates what the full state trie would be (tds.ResolveStateTrie) in the relevant parts only (it ignores parts that aren't touched by the current block). This trie only has the hashes, and it's loaded from the IntermediateTrieHash bucket. After the resolve call, the new root is calculated by modifying the trie according to the touched accounts in the block. This is implemented in `turbo/trie/stream.go:HashWithModifications` and downwards, and it's definitely not an easy code to follow.

It's not 100% clear to me from where the intermediate hashes are written yet. I've seen modifications of the bucket for pruning deleted accounts, and mostly reading, but haven't found where the puts are coming from.
