### ISSUE TITLE
Geth version is not set correctly between releases

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1580]
## Description

Getting the version from geth  on master (ab78658ae3a738d91d877f289e37fead2a0f1cf7) reports 1.0.0-unstable which is wrong.

```
$ ./celo-blockchain/build/bin/geth version 
Celo
Version: 1.0.0-unstable
Git Commit: ab78658ae3a738d91d877f289e37fead2a0f1cf7
Git Commit Date: 20210527
Architecture: amd64
Protocol Versions: [66 65 64]
Go Version: go1.16.4
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go
```

## Proposed Solution

The variables in `params/version.go` need to be updated to reflect the correct version and we need to make this part of the release process.

**Comment by piersy** [comment]
@oneeman maybe this is something you could look into, given that you seem to be managing the releases.

**Comment by oneeman** [comment]
Since we use release branches, the commits on master don't correspond to the released versions, except perhaps the first released version from a release branch (e.g. v1.3.0-beta).  There is no commit on master that is equivalent to v1.3.2

Given that, I don't think having master now say v1.3.2 would be an improvement, and it's not at all clear to me what would be the "correct version" that it should say.

Now, I do agree that 1.0.0-unstable is misleading, and that it provides less information than we would like.  So perhaps we should try to think of what it should be instead?  My first thought was something like "1.4.0-master" or something like that, since master is the branch from which the next release branch will be cut.  But I don't really like it.  Maybe "1.3.0-master" to reflect the latest release branch even though master is ahead of that?

**Comment by oneeman** [comment]
Another reason to change it is that having it always say "1.0.0-unstable" means that the "minimum client version" functionality  won't work as desired (if we increased the minimum client version then master would become unusable on that network).
