### ISSUE TITLE
Inconsistent extraData returned in block data

### ISSUE THREAD

**Issue by quickchase** [celo-org/celo-blockchain#1930]
## Description

Celo nodes seem to be returning different values under `extraData` for the same block.

## Current Behavior

Call:
```
{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByHash","params":["0x1c2ccac114a178c2226abd15b614c487e39564208ee4c76a207bb6fd39340033",false]}
```

Grep result for `17ddb`
![image](https://user-images.githubusercontent.com/87909910/179548872-dcd98764-94bd-4899-83a8-ae2160de307e.png)

As you can see there are 3 different outputs here:
```
17ddbb5d
17ddbfdc
17ddbf5c
```

All nodes are `celo/v1.5.5-stable-573df8e1/linux-amd64/go1.18.3`

As far as I can tell all other fields in the block that is returned are the same on all nodes, it's only `extraData` that is returning different values. I checked `number`, `gasUsed`, `hash`, `totalDifficulty` it all matches up.

**Comment by carterqw2** [comment]
This is expected. The `extraData` field among other things contains an aggregated BLS signature based on at least 2/3rds of signatures the given validator has received. Since different validators might receive a different set of signatures at different times, the aggregated BLS signature might vary as well. Therefore, this part is excluded from the block hash calculation.
