### ISSUE TITLE
receiptsRoot calculation doesnt match the blockheader

### ISSUE THREAD

**Issue by sirpy** [celo-org/celo-blockchain#1944]
I'm trying to calculate the receiptsRoot in javascript, the code I have works for both ethereum and fuse,
but when running on a celo block the resulting receiptsRoot doesnt match the one returned at the blockheader

```
import * as ethers from 'ethers';
import { JsonRpcBatchProvider } from '@ethersproject/providers'
import Tree from "merkle-patricia-tree"
import { Receipt, Proof } from "eth-object"
import { encode } from "eth-util-lite"
import { promisfy } from "promisfy"

export const receiptProof = async (txHash: string, provider: ethers.providers.JsonRpcProvider, chainId?: number) => {
  const targetReceipt = await provider.send("eth_getTransactionReceipt",[txHash])
  if (!targetReceipt) { throw new Error("txhash/targetReceipt not found. (use Archive node)") }

  const rpcBlock = await provider.send("eth_getBlockByHash",[targetReceipt.blockHash,false])
  const withReceiptType = !!rpcBlock.baseFeePerGas || [42220].includes(chainId)
  const receipts = await Promise.all(rpcBlock.transactions.map(async (siblingTxHash) => {
    return provider.send("eth_getTransactionReceipt",[siblingTxHash])
  }))
  
  const tree = new Tree();

  await Promise.all(receipts.map((siblingReceipt, index) => {
    const siblingPath = encode(index)
    let serializedReceipt = Receipt.fromRpc(siblingReceipt).serialize()
    if(withReceiptType && siblingReceipt.type && siblingReceipt.type != '0x0')
    {
      serializedReceipt = Buffer.concat([Buffer.from([siblingReceipt.type]),serializedReceipt])
    }
    return promisfy(tree.put, tree)(siblingPath, serializedReceipt)
  }))

  const [,,stack] = await promisfy(tree.findPath, tree)(encode(targetReceipt.transactionIndex))
  const receiptsRoot = "0x"+tree.root.toString("hex")
  if(receiptsRoot !== rpcBlock.receiptsRoot)
  {
    console.error({receiptsRoot, blockReceiptsRoot:rpcBlock.receiptsRoot})
    throw new Error("receiptsRoot mismatch")
  }
  return {
    receiptsRoot,
    receiptProof: Proof.fromStack(stack).raw.map(_ => "0x"+encode(_).toString("hex")),
    txIndex: targetReceipt.transactionIndex,
    receiptRlp: "0x"+(withReceiptType && targetReceipt.type && targetReceipt.type != '0x0' ? ethers.utils.hexlify(Number(targetReceipt.type)).slice(2) : '')+Receipt.fromRpc(targetReceipt).serialize().toString("hex")
  }
}
```

running the following throws the exception only on celo, i've tried txs from other blocks, same result
```
    fuseProof = await receiptProof("0x8770fb92888d3ff30dfc96040a9371872737318c81e6ca1cb2b0e88ad981e627",new ethers.providers.JsonRpcBatchProvider("https://rpc.fuse.io"))
    ethProof = await receiptProof("0x32ba5e829fc530871442755ad770693c7fadf7160f271d0e572dd9453f5adaaa",new ethers.providers.JsonRpcProvider("https://cloudflare-eth.com/v1/mainnet"))
  celoProof = await receiptProof("0x67b389bc4640211455cfc7234fec76ce7cd90198b594a427b7935bda17bd940d",new ethers.providers.JsonRpcBatchProvider("https://forno.celo.org"), 42220)
```

**Comment by piersy** [comment]
Hi @sirpy in Celo there exists an extra receipt called the block receipt which includes logs emitted by EVM calls made by the system. The block receipt is positioned at the end of the transaction receipts and can be fetched by calling `eth_getBlockReceipt` and providing the block hash. So if you add the block receipt to the end of `receipts` I believe your receipt root calculation should then be correct.

**Comment by sirpy** [comment]
@piersy awesome that worked.

**Comment by sirpy** [comment]
@piersy this is now broken again since block 15988682
i've tested many blocks and it works for blocks before 15988682, but from block 15988682 the calculation no longer matches the receiptsroot in the blockheader

**Comment by hbandura** [comment]
@sirpy can you provide more info? what is the value that you get adding exactly which receipts? So I can find the problem

**Comment by sirpy** [comment]
@hbandura i'm not sure what you mean, the above code works for every block before 15988682 and fails for every code after 15988682.
The best way for you to play with it is:
1. clone https://github.com/GoodDollar/GoodBridge
2. yarn install
3. in __tests__/mpt.test.ts add `.only` to the celo test `it('generate receipt proof for celo'`
4. run yarn test __tests__/mpt.test.ts
5. in the test you can play with different blocks by changing the input to some TRANSACTION hash from the block you want to test.

Once you run the test the error with receipts in printed to the console.
You can also reach me on telegram as @sirpy

**Comment by hbandura** [comment]
thanks, I'll try that out

**Comment by hbandura** [comment]
I reviewed the code and found that the serialization of receipt 0 is different. And the reason seems to be a bug on the celo-blockchain side: from the moment we implemented a filter for receipts to fix the ethersjs incompatibility issue, the 'type' value stopped being serialized to JSON. So without that information, from a client it would appear as if the transaction had the type 0.

Your serialization of tx with index 0:
```
f9010901830181a2b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0
```

Celo blockchain serialization of tx 0
```
02f9010901830181a2b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0
```

I went ahead and requested the full Tx in your code before the receipt, and used the tx.type instead of receipt.type, and it worked without issues, so that confirms the problem.

This bug was introduced in the node version 1.7.0. So if you run a node with 1.6.0 it will definitely not have that problem. I will raise this bug in order to provide a patch and create v1.7.1 so forno will be upgraded. The fix is basically adding a line, and making sure no other thing is missing.

**Comment by sirpy** [comment]
so the temporary fix on my side is to add the receipt type to the first receipt even if it is type 0?
the rest of the receipts do not require type0 added?

**Comment by hbandura** [comment]
the serialization code does not add the type if the type is zero. This is done correctly on both your code and in celo-blockchain side.

a temporary fix could be to:
1) try to get the tx type from a different rpc method, and use that instead of the recipe.type.
2) instead of using forno, use the rpc of a node that is running a previous version. (1.6.0 won't have this problem. I believe 1.6.1 is also ok)

Due to a majority of txs with type 0, if adding an rpc cost is too expensive, you could try doing it only if you get a discrepancy in the merkle root calculation, but it would be a slight loss of security due to the (incredibly rare) possibility of a collision and an intentional fraud by the node)

**Comment by sirpy** [comment]
@hbandura i fail to understand.
1. according to your initial report I see an extra "0" at the beginning on the "blockchain" side. so that means that if I want to get the same merkle hash I should serialize the receipt on my side with an extra 0.
2. if the receipt type is missing it is the same as receipt type "0". so I don't see why taking the receipt type from another source would make any difference in case all receipts are of type 0.

**Comment by hbandura** [comment]
1) No:
It's not an "0", it's an "02", because it's a tx type 2. when tx type is not zero, it gets serialized before the rest of the data.

2) the receipt type is always missing in the receipt json obj. that's the bug in celo-blockchain's rpc. however it's not missing in the tx json obj.



Btw, I went ahead and checked and I believe this is an actually much older bug than what I told you yesterday. I'm currently working on a patch. Hopefully it can be released next week.

**Comment by hbandura** [comment]
1.7.1 is already out with the fix, this can probably be closed

**Comment by sirpy** [comment]
Ok I'll try again, though I did notice the type is missing, and Im 99% sure I've already tried with calling gettransaction instead of gettxreceipt but I'll try again

**Comment by sirpy** [comment]
@hbandura can you also look at this issue:
https://github.com/celo-org/celo-blockchain/issues/1981
