### ISSUE TITLE
`--dev.period` flag does not override DevChainConfig block period 

### ISSUE THREAD

**Issue by kamikazechaser** [celo-org/celo-blockchain#2007]
## Description

The `--dev.period` should override the block time, but the block time remains 1s.

## Context

Improve dev net setup.

**Comment by eelanagaraj** [comment]
Hey @kamikazechaser could you share the command that you tried to run & celo-blockchain version?

Trying to run in dev mode on master fails for me and from initially digging into this, looks pretty broken.

**Comment by kamikazechaser** [comment]
`--dev  --miner.validator 47e172f6cfb6c7d01c1574fa3e2be7cc73269d95` (That is the hard coded public key) For starting in dev mode, default block time is 1s. I directly modified the block time to 5s and re-compiled it for my own testing.

**Comment by eelanagaraj** [comment]
Yeah so even when I provide the hard-coded key, (on `master`) I get a fatal error:
```
INFO [03-13|12:23:28.684] Starting Geth in ephemeral dev mode...
INFO [03-13|12:23:28.685] Maximum peer count                       ETH=175 LES=0 total=175
INFO [03-13|12:23:28.685] Set global gas inflation rate            rate=1.300
INFO [03-13|12:23:28.685] Set global gas cap                       cap=25,000,000
Fatal: Failed to unlock developer account: no key for given address or file
```

I can only get this to sort of work when using a persistent datadir in `--dev` mode & making a keystore file available with the public key (this doesn't seem to be the intended behavior of this mode, but seems to have broken a while back). It then seems like you'd need to manually deploy the registry/smart contracts in order to do anything beyond this. I'll take a look at this specific parameter, but depending on your use case, it may be more helpful to check out using `mycelo` to run a testnet locally! (If you have already checked it out and you prefer dev mode, any additional context/feedback would be super helpful there! 🙏)

**Comment by kamikazechaser** [comment]
> I can only get this to sort of work when using a persistent datadir in --dev mode & making a keystore file available with the public key (this doesn't seem to be the intended behavior of this mode, but seems to have broken a while back).

Correct, the first start needs to be without the miner.validator flag so that the key gets automatically populated in the data dir.

Afaik, we got it to work without deploying any contracts.

>  mycelo to run a testnet locally

I see, we didn't come across it then but it could be useful in the future.

cc/ @nolash

**Comment by eelanagaraj** [comment]
> Afaik, we got it to work without deploying any contracts.

Block production should work but do you get consistent errors regarding a registry address check?

Just put up a PR that should fix this flag issue & mostly fix dev mode (i.e. allow you to use it in one step with `geth --dev` or with a datadir), hopefully does the trick for y'all 🤞

And yeah, I'd recommend checking out mycelo for any more complicated dev testnet stuff (for instance, it also lets you easily set up a local testnet with more than 1 node, and it creates a genesis file with all core contracts so may be more useful if testing any smart contract txs). From what I can tell it's also better maintained/more used than `--dev` functionality 😅
