### ISSUE TITLE
wrong result for eth_gasPrice

### ISSUE THREAD

**Issue by sirpy** [celo-org/celo-blockchain#2136]
## Expected Behavior
should return 5gwei or current baseFeePerGas

## Actual Behavior

returns 25gwei

## Steps to reproduce the behavior

```
curl https://forno.celo.org/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
```

Seems to work fine on Baklava
Chain/Network: `Alfajores/Mainnet`

**Comment by palango** [comment]
@sirpy Currently this endpoint returns a suggested gas price that works in the given network condition and not the base fee.

https://github.com/celo-org/celo-blockchain/blob/d8b368055a87ab178f007eed612c7da7d3d1b0c9/contracts/gasprice_minimum/gasprice_minimum.go#L65-L68

On baklava the values matches your expectation because the base fee is lower (1gwei) and the multipler is 5.

One solution to better handle this would be to create two endpoints, one for the base fee (similar to ethereum) and one for the suggested fee. What do you think about that?

**Comment by sirpy** [comment]
@palango sure, matching with ethereum standards would be best

**Comment by sirpy** [comment]
@palango though i dont think on any other network the get gas price returns a multiplier of the current gas costs.
the 5x multiplier is also very very high, it should be something like 1.2

**Comment by palango** [comment]
@sirpy In the next release you will be able to change the multiplier with the `--rpc.gaspricemultiplier` option. The default changes two a factor of two, but maybe we will change that on forno.

Further changes to get closer to Ethereum are tracked in https://github.com/celo-org/celo-blockchain/issues/2153

**Comment by sirpy** [comment]
@palango 
I don't think that's a solution as users and dapps dont use their own rpc.
They rely on forno or other providers.
Currently in many celo dapps users are paying 5x for gas
