### ISSUE TITLE
Devs SBAT add more functionality to the geth attach REPL

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-blockchain#353]
### Expected Behavior

Validators and groups can manage themselves via `geth attach` 

### Current Behavior

Need to spin up separate CLI

**Comment by mcortesi** [comment]
@cmcewen made an interesting comment the other day, more or less like:

Smart contract have their own release schedule. We change them by governance for example. But the geth nodes won't change due to that. If our get attach api is coupled to the contracts, we need to be careful to update geth whenever some governance approval changes the contracts.
