### ISSUE TITLE
Intermittent test failure in keystore_test

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#782]
```
--- FAIL: TestWalletNotifications (0.59s)
    keystore_test.go:344: wallet list doesn't match required accounts: have 541, want 540
    keystore_test.go:372: can't find event with Kind=0 for a91e42fdafd05897598dd5a28219a125ffde0218
FAIL
```

**Comment by howydev** [comment]
hi tim and mariano! i'd love to attempt this. you said it's intermittent, is there any reliable way of recreating the error?

**Comment by oneeman** [comment]
Thanks @howydev! Sorry for the late reply.  It looks like this has been fixed upstream recently (https://github.com/ethereum/go-ethereum/pull/21703), so we can cherry-pick the fix (I'll open up a PR).

To answer your question, what I usually do to recreate intermittent test failures is run the test many times, using the `-count` argument.  For this test it would be something like:

```
go test ./accounts/keystore -run ^TestWalletNotifications$ -count 50 
```

However, with this test I couldn't get it to fail.  In some cases, tests fail in CI that don't fail locally (I imagine it's because the CI machines are slower), which makes things harder, and that seems to be the case with this one.
