### ISSUE TITLE
Panic on full node in Downloader.findAncestor

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#828]
Observed by Thylacine on Discord

> Hi team, keep getting sigfault / kernel panic type errors on my full node:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xaf416d]

goroutine 389 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc01957aa80, 0xc01b464960, 0xc01b7b9200, 0x0, 0x0, 0xc000053180)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:853 +0x15ad
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc01957aa80, 0xc01b464960, 0x61a8d329a8bd6f45, 0x30537172303a2aa5, 0x95e87575d2802ce9, 0xc0633a0e3e8eafc8, 0xc01bb50b20, 0x0, 0x0)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:464 +0x37d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc01957aa80, 0xc01b550430, 0x10, 0x61a8d329a8bd6f45, 0x30537172303a2aa5, 0x95e87575d2802ce9, 0xc0633a0e3e8eafc8, 0xc01bb50b20, 0x0, 0x0, ...)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:433 +0x362
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc01957aa80, 0xc01b550430, 0x10, 0x61a8d329a8bd6f45, 0x30537172303a2aa5, 0x95e87575d2802ce9, 0xc0633a0e3e8eafc8, 0xc01bb50b20, 0x0, 0x40, ...)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:351 +0x91
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc01957e4b0, 0xc01b4d0a80)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:200 +0x313
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x1df
```

Seg fault corresponds to the following code section https://github.com/celo-org/celo-blockchain/blob/3ab1440abb60750981907de68edd625c6e2ef277/eth/downloader/downloader.go#L852-L856

A comment indicates that an unsafe pointer dereference is performed because it should "never" be `nil`. That assumption is clearly being broken somewhere.

**Comment by oneeman** [comment]
Closing this and #723 as stale.  There were 3 reports (one here and two in #723) were all reported around the end of 2019, beginning of 2020, and the problem hasn't reappeared since as far as we know.

As @tkporter pointed in #723, there were issues on go-ethereum with the same crash, suggesting chain corruption and/or too many open files.  But the celo repo had already included the upstream fix for the issue that was causing it for go-ethereum (and which was only on MacOS), so it's unlikely to be exactly the same.  Still, since it hasn't happened in nearly a year it has likely been fixed already, and at any rate we can't identify the cause without someone being able to reproduce the cause.
