### ISSUE TITLE
Builds reliably green

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#847]
Our CI builds are not 100% reliable. There are several tests that are flaky; and we are unsure if that's because of the test or because of a bug.

In any case, we should fix those flaky tests.

Things to do:

  - [ ] Make a list of all flaky tests (& create an issue for each)
  - [ ] Fix issues for flaky tests 

Circle CI tracks flaky tests, see [here](https://app.circleci.com/insights/github/celo-org/celo-blockchain/workflows/build/tests) currently 169 flaky tests identified.

**Comment by jfoutts-celo** [comment]
A survey of recent failures finds three frequent offenders:

celo-blockchain: coverage and unit-tests: All the unit tests run successfully but then apparently `go test` fails afterwards.

celo-monorepo / celo-blockchain: end-to-end-geth-governance-test: when the validator set is changing: There's some indeterminacy occurring here and some likely suspects, such as:
```
      // Wait for the current epoch to complete.
      await sleep(epoch)
```

celo-monorepo: the kaniko docker leaderboard build is failing.  I need some kaniko and GCP expertise for this one.  The leaderboard docker build succeeds on my laptop.  GCP says `Unable to retrieve build log` for me.  No other details on why it failed.

**Comment by jfoutts-celo** [comment]
Also some less frequently occurring indeterminacy affecting end-to-end-sync-test

**Comment by jfoutts-celo** [comment]
Also flaky:

governance_tests > when the validator set is changing > should block propose in a round robin fashion

end-to-end-geth-transfer-test > Transfer with changed intrinsic gas cost > ultralight Node > when there is no demurrage > hen setting a gas amount greater than the amount of gas necessary.  e.g. https://circleci.com/gh/celo-org/celo-monorepo/123787

**Comment by jeanregisser** [comment]
The `cli-test` became flaky from what I see.

Exampe: https://app.circleci.com/jobs/github/celo-org/celo-monorepo/129115

**Comment by jfoutts-celo** [comment]
Also PRs: 
- https://github.com/celo-org/celo-monorepo/pull/2766
- https://github.com/celo-org/celo-monorepo/pull/3044

**Comment by piersy** [comment]
I've reopened this issue because I'm seeing lots of flaky tests in CI. All these tests went green simply by being re-run some number of times.

Current offenders are:
* [unit-tests](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/19981a18-c777-4f0d-aa75-940b7d7f39ce/jobs/54765) [2](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/1fd35358-f351-4b80-9057-a45b2e0a1a03/jobs/54739) [3](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/865a5378-06e5-4653-a2eb-6c89f38dd4a0/jobs/54752) [4](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5755/workflows/9e4a6ae4-0197-4d36-b851-9e13cba42173/jobs/54917)
* [coverage](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/865a5378-06e5-4653-a2eb-6c89f38dd4a0/jobs/54753) [2](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/1fd35358-f351-4b80-9057-a45b2e0a1a03/jobs/54737) [3](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5740/workflows/19981a18-c777-4f0d-aa75-940b7d7f39ce/jobs/54764) [5](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5754/workflows/c7b50f8c-19d5-4cc3-8ddb-869c8e38166e/jobs/54898) [6](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5754/workflows/bde8178a-b24c-4759-9510-21753ad7d13d/jobs/54908)
* [end-to-end-transfer-test](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5753/workflows/2d01ed99-e2a4-48c5-94f2-bc8e23ea9cef/jobs/54887) [2](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5754/workflows/c7b50f8c-19d5-4cc3-8ddb-869c8e38166e/jobs/54903)
* [end-to-end-governance-test](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5754/workflows/c7b50f8c-19d5-4cc3-8ddb-869c8e38166e/jobs/54904) [2](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/5754/workflows/bde8178a-b24c-4759-9510-21753ad7d13d/jobs/54906)

**Comment by trianglesphere** [comment]
Notion doc: https://www.notion.so/clabsco/Flaky-Test-Tracking-46d29c428f90461b9ff7279e9c7a615b

**Comment by piersy** [comment]
Also seeing this test [TestUDPv4_LookupIterator ](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/6646/workflows/178b3d6d-d143-424f-a37f-00b60d06c211/jobs/64830) failing randomly

**Comment by piersy** [comment]
Also seeing this tests TestServerInboundThrottle being flaky

**Comment by piersy** [comment]
Aslo
TestAnnounceGossipQueryMsg
TestPrepare
https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/7026/workflows/a702ac16-f5b6-4f1d-9254-11b6f02d17a7/jobs/69372

**Comment by piersy** [comment]
Also
TestIPCAttachWelcome
https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/7144/workflows/7e22a2ca-2b54-4456-8d18-74a849e64376/jobs/71092

**Comment by piersy** [comment]
Also TestStartStopValidators - https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/7232/workflows/1f60a0c6-dae3-4492-ba0a-c5743de15e0b/jobs/72398

It timed out after 46 seconds, normally it runs on my machine in 12 seconds. So i think this could be a deadlock that appears to happen very rarely.
```
--- FAIL: TestStartStopValidators (41.63s)
    e2e_test.go:159: 
        	Error Trace:	e2e_test.go:159
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestStartStopValidators
FAIL
coverage: 50.4% of statements in ./consensus/istanbul/...
FAIL	github.com/celo-org/celo-blockchain/e2e_test	44.634s
FAIL
```

**Comment by piersy** [comment]
Further TestPrepare [fail](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/7871/workflows/0aea30f5-9ee7-47ed-8a7a-52c2d6c860f0/jobs/81510) today
```
=== RUN   TestPrepare
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0a2f2]

goroutine 577 [running]:
github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).newChainHeadLoop(0xc00c682800, 0xc00d9be000)
	/home/circleci/repos/geth/consensus/istanbul/backend/engine.go:637 +0x92
created by github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).SetChain
	/home/circleci/repos/geth/consensus/istanbul/backend/engine.go:626 +0xaa
FAIL	github.com/celo-org/celo-blockchain/consensus/istanbul/backend	22.174s
?   	github.com/celo-org/celo-blockchain/consensus/istanbul/backend/backendtest	[no test files]
```
