### ISSUE TITLE
Remove SignHash from Wallet interface

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-blockchain#861]
### Expected Behavior

Deprecated `SignHash` is not exposed in `Wallet` or used anywhere in other packages.

### Current Behavior

`SignHash` is used for backwards compatibility with 1.8.

For reference: #859, #860.

**Comment by hbandura** [comment]
SignHash is currently being used by `consensus/istanbul/backend/random.go` in `GenerateRandomness(...)`. This is used to generate the random seed that will eventually produce the randomness commitment for a validator. While in theory the generation could be changed, since it should only be used for validators that haven't created one yet, the implementation often reverts to regenerating a previous seed (haven't dig down on why). So removing the SignHash would effectively break this for all validators that have already generated their randomness commitments.

Unless we can assert that the seed needs not be regenerated ever, we cannot change this.
